[package]
name = "flatten"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_flatten"
crate-type = ["cdylib"]
path = "rust_flatten.rs"

[dependencies]
pyo3 = { git = "https://github.com/pyo3/pyo3", features = ["extension-module"] }